pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'nadahassan2024'
        APP_IMAGE = 'webapptest'
        DB_IMAGE = 'db'
        TAG = 'latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Nadasawah90/Deploy-app-using-jenkins-file-pipline-.git'
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    dir('Dockerfiles/App') {
                        sh "docker build -t ${DOCKERHUB_USER}/${APP_IMAGE}:${TAG} ."
                    }
                }
            }
        }

        stage('Build DB Image') {
            steps {
                script {
                    dir('Dockerfiles/DB') {
                        sh "docker build -t ${DOCKERHUB_USER}/${DB_IMAGE}:${TAG} ."
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo $PASS | docker login -u $USER --password-stdin
                        docker push ${DOCKERHUB_USER}/${APP_IMAGE}:${TAG}
                        docker push ${DOCKERHUB_USER}/${DB_IMAGE}:${TAG}
                        docker logout
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    # Apply only Kubernetes YAML files
                    kubectl apply -f .
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Build and deployment completed successfully."
        }
        failure {
            echo "❌ Pipeline failed. Check logs."
        }
    }
}
